BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "bbai64"
BBFILE_PATTERN_bbai64 = "^${LAYERDIR}/"

# Priority 14 — sits above meta-edgeai (13) so our bbappends win
BBFILE_PRIORITY_bbai64 = "14"

LAYERDEPENDS_bbai64 = "core meta-arago-distro meta-ti-bsp openembedded-layer"
LAYERSERIES_COMPAT_bbai64 = "scarthgap"
